test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -46,52 +46,62 @@ jobs:
         with:
           node-version: ${{ steps.nvm.outputs.NVMRC }}
 
-      - name: Bootstrap packages
-        run: npm run bootstrap
-
-      - name: Lint
-        run: npm run lint
-
-      - name: Lint markdown
-        run: npm run lint:markdown
-
-      - name: Type checks
-        run: npm run type-check
-
-      - name: Run tests
-        run: npm test
-
-      - name: Set Inso CLI variables
-        id: inso-variables
+      - name: tests
         shell: bash
         run: |
-          INSO_VERSION="${{ needs.get_version.outputs.inso-version }}-run.${{ github.run_number }}"
-          PKG_NAME="inso-${{ matrix.os }}-$INSO_VERSION"
-          BUNDLE_ID="com.insomnia.inso"
+          NOW=$(date +"%M")
+          LAST=$(echo $NOW | tail -c 2)
 
-          echo ::set-output name=pkg-name::$PKG_NAME
-          echo ::set-output name=bundle-id::$BUNDLE_ID
-          echo ::set-output name=inso-version::$INSO_VERSION
+          if [ $LAST -gt 5 ]; then
+            echo "Failed"
+            exit 1
+          fi
+      # - name: Bootstrap packages
+      #   run: npm run bootstrap
 
-      - name: Package Inso CLI binary
-        run: npm run inso-package
-        env:
-          VERSION: ${{ steps.inso-variables.outputs.inso-version }}
+      # - name: Lint
+      #   run: npm run lint
 
-      - name: Codesign & create macOS installer
-        if: matrix.os == 'macos-latest'
-        run: |
-          chmod +x ./src/scripts/macos-pkg.sh
-          ./src/scripts/macos-pkg.sh
-        shell: bash
-        working-directory: packages/insomnia-inso
-        continue-on-error: true
-        env:
-          MACOS_CERTIFICATE: ${{ secrets.DESIGNER_MAC_CSC_LINK }}
-          MACOS_CERTIFICATE_PWD: ${{ secrets.DESIGNER_MAC_CSC_KEY_PASSWORD }}
-          PKG_NAME: ${{ steps.inso-variables.outputs.pkg-name }}
-          BUNDLE_ID: ${{ steps.inso-variables.outputs.bundle-id }}
-          VERSION: ${{ steps.inso-variables.outputs.inso-version }}
+      # - name: Lint markdown
+      #   run: npm run lint:markdown
+
+      # - name: Type checks
+      #   run: npm run type-check
+
+      # - name: Run tests
+      #   run: npm test
+
+      # - name: Set Inso CLI variables
+      #   id: inso-variables
+      #   shell: bash
+      #   run: |
+      #     INSO_VERSION="${{ needs.get_version.outputs.inso-version }}-run.${{ github.run_number }}"
+      #     PKG_NAME="inso-${{ matrix.os }}-$INSO_VERSION"
+      #     BUNDLE_ID="com.insomnia.inso"
+
+      #     echo ::set-output name=pkg-name::$PKG_NAME
+      #     echo ::set-output name=bundle-id::$BUNDLE_ID
+      #     echo ::set-output name=inso-version::$INSO_VERSION
+
+      # - name: Package Inso CLI binary
+      #   run: npm run inso-package
+      #   env:
+      #     VERSION: ${{ steps.inso-variables.outputs.inso-version }}
+
+      # - name: Codesign & create macOS installer
+      #   if: matrix.os == 'macos-latest'
+      #   run: |
+      #     chmod +x ./src/scripts/macos-pkg.sh
+      #     ./src/scripts/macos-pkg.sh
+      #   shell: bash
+      #   working-directory: packages/insomnia-inso
+      #   continue-on-error: true
+      #   env:
+      #     MACOS_CERTIFICATE: ${{ secrets.DESIGNER_MAC_CSC_LINK }}
+      #     MACOS_CERTIFICATE_PWD: ${{ secrets.DESIGNER_MAC_CSC_KEY_PASSWORD }}
+      #     PKG_NAME: ${{ steps.inso-variables.outputs.pkg-name }}
+      #     BUNDLE_ID: ${{ steps.inso-variables.outputs.bundle-id }}
+      #     VERSION: ${{ steps.inso-variables.outputs.inso-version }}
 
       # We don't need to notarize and staple on every commit
       # - name: Notarize installer
@@ -118,32 +128,32 @@ jobs:
       #     appstore-connect-username: ${{ secrets.DESIGNER_APPLE_ID }}
       #     appstore-connect-password: ${{ secrets.DESIGNER_APPLE_ID_PASSWORD }}
 
-      - name: Create Inso CLI artifacts
-        run: npm run inso-package:artifacts
-        env:
-          VERSION: ${{ steps.inso-variables.outputs.inso-version }}
+      # - name: Create Inso CLI artifacts
+      #   run: npm run inso-package:artifacts
+      #   env:
+      #     VERSION: ${{ steps.inso-variables.outputs.inso-version }}
 
-      - name: Upload Inso CLI artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          if-no-files-found: ignore
-          name: ${{ steps.inso-variables.outputs.pkg-name }}
-          path: packages/insomnia-inso/artifacts
+      # - name: Upload Inso CLI artifacts
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     if-no-files-found: ignore
+      #     name: ${{ steps.inso-variables.outputs.pkg-name }}
+      #     path: packages/insomnia-inso/artifacts
       
-      - name: Run Inso CLI smoke tests
-        run: npm run test:smoke:cli
+      # - name: Run Inso CLI smoke tests
+      #   run: npm run test:smoke:cli
 
-      - name: Build app for smoke tests
-        run: npm run app-build:smoke
+      # - name: Build app for smoke tests
+      #   run: npm run app-build:smoke
 
-      - name: Run app smoke tests
-        timeout-minutes: 10 # sometimes jest fails to exit - https://github.com/facebook/jest/issues/6423#issuecomment-620407580
-        run: npm run test:smoke:build
+      # - name: Run app smoke tests
+      #   timeout-minutes: 10 # sometimes jest fails to exit - https://github.com/facebook/jest/issues/6423#issuecomment-620407580
+      #   run: npm run test:smoke:build
 
-      - name: Upload smoke test screenshots
-        uses: actions/upload-artifact@v2
-        if: always()
-        with:
-          if-no-files-found: ignore
-          name: ${{ matrix.os }}-smoke-test-screenshots-${{ github.run_number }}
-          path: packages/insomnia-smoke-test/screenshots
+      # - name: Upload smoke test screenshots
+      #   uses: actions/upload-artifact@v2
+      #   if: always()
+      #   with:
+      #     if-no-files-found: ignore
+      #     name: ${{ matrix.os }}-smoke-test-screenshots-${{ github.run_number }}
+      #     path: packages/insomnia-smoke-test/screenshots
